- name: install older version of apache
  hosts: all
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
      when: httpd_version!='latest'
      notify: restart apache
    - name: enable apache
      service:
        name: httpd
        state: started
    - name: create firewall rule
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
