- name: install older version of apache
  hosts: all
  tasks:
    - name: install apache
      register: updatesys
      yum:
        name: httpd
        state: present
        update_cache: true
       
       # cache_valid_time: 3600
      notify: restart apache
    - name: display update
      debug:
        msg: "{{updatesys.stdout_lines|last}}"
    - name: enable apache
      service:
        name: httpd
        state: started
    - name: create firewall rule
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
